In [1]:
import numpy as np

In [2]:
a = np.random.rand(5)
print(a)

[0.05740485 0.56453011 0.40115557 0.48333369 0.00113661]


In [3]:
a.shape

(5,)

In [4]:
print(a.T)

[0.05740485 0.56453011 0.40115557 0.48333369 0.00113661]


In [5]:
print(a @ a.T)

0.7165281076588883


# NumPy Broadcasting & 1D Array Pitfalls

- A 1D NumPy array (shape `(n,)`) is **not** a row or column vector.
- `.T` has no effect on a 1D array → shape stays `(n,)`.
- The operation `a @ a.T` with shape `(n,)` is just a **dot product**, returning a scalar — not a matrix.
- For broadcasting to work as expected (row vs. column), reshape explicitly:
  - `(n, 1)` → column vector  
  - `(1, n)` → row vector
- Only after reshaping can you properly perform outer products `(n,1) @ (1,n)` or inner products `(1,n) @ (n,1)`.
- **Takeaway**: Always reshape `(n,)` arrays when you need clear matrix behavior in broadcasting.

In [6]:
b = np.random.rand(5,1)
print(b)

[[0.5586829 ]
 [0.99103463]
 [0.92434253]
 [0.74025868]
 [0.22987447]]


In [7]:
print(b.T)

[[0.5586829  0.99103463 0.92434253 0.74025868 0.22987447]]


In [8]:
print(b@b.T)

[[0.31212659 0.5536741  0.51641437 0.41356987 0.12842693]
 [0.5536741  0.98214964 0.91605546 0.73362199 0.22781356]
 [0.51641437 0.91605546 0.85440912 0.68425259 0.21248275]
 [0.41356987 0.73362199 0.68425259 0.54798292 0.17016657]
 [0.12842693 0.22781356 0.21248275 0.17016657 0.05284227]]


In [9]:
print(b.T@b)

[[2.74951053]]


print(b@b.T)

In [10]:
assert(b.shape == (5,1))
assert(a.shape == (5,1))

AssertionError: 